from dataclasses import dataclass
from enum import Enum

class ProductStatus(str, Enum):
    ACTIVE = "active"
    DISCONTINUED = "discontinued"
    SEASONAL_HOLD = "seasonal_hold"


@dataclass(frozen=True)
class DraftPurchaseOrder:
    """Structure for an untrusted purchase order generated by the AI agent."""
    store_id: str
    sku: str
    quantity: int
    reasoning: str          
    cited_sales_window: str 


@dataclass(frozen=True)
class ValidationResult:
    is_valid: bool
    requires_human_approval: bool
    errors: list[str]
    warnings: list[str]


# CORE DATABASE INTERFACES

class InventorySystem:
    """
    Unified gateway to fetch live source-of-truth records.
    Acts as the data grounding layer to verify agent assertions.
    """
    def __init__(self, warehouse_db, product_db, sales_db):
        self._warehouse = warehouse_db
        self._products = product_db
        self._sales = sales_db

    def get_product_status(self, sku: str) -> ProductStatus:
        return self._products.get_status(sku)

    def get_available_stock(self, sku: str) -> int:
        return self._warehouse.get_quantity(sku)

    def get_recent_order_sizes(self, store_id: str, sku: str, lookback_days: int = 90) -> list[int]:
        return self._sales.get_past_order_quantities(store_id, sku, lookback_days)

    def get_actual_sales_velocity(self, store_id: str, sku: str, window: str) -> int | None:
        return self._sales.get_units_sold(store_id, sku, window)


# GUARDRAIL VALIDATION LAYER

class PurchaseOrderValidator:
    """
    Zero-trust validation engine that runs hardcoded business logic checks
    on agent proposals before any order is dispatched to procurement APIs.
    """
    
    # absolute ceiling for unreviewed automated orders
    HUMAN_REVIEW_QUANTITY_THRESHOLD = 500
    
    # multiple allowed above historical ordering baseline before triggering anomaly flags
    ANOMALY_MULTIPLIER = 3.0

    def __init__(self, inventory: InventorySystem):
        self._inventory = inventory

    def validate(self, order: DraftPurchaseOrder) -> ValidationResult:
        """Evaluates a proposed order against physical inventory and status boundaries."""
        errors: list[str] = []
        warnings: list[str] = []

        # run sequential safety checks
        self._check_schema_sanity(order, errors)
        self._check_product_lifecycle(order, errors)
        self._check_warehouse_constraints(order, errors)
        self._verify_cited_sales_data(order, warnings)
        self._check_order_size_anomaly(order, warnings)

        # flag for manual verification if exceptions occur or size caps are exceeded
        requires_human = (
            bool(warnings)
            or order.quantity >= self.HUMAN_REVIEW_QUANTITY_THRESHOLD
        )

        return ValidationResult(
            is_valid=not errors,
            requires_human_approval=requires_human,
            errors=errors,
            warnings=warnings,
        )

    def _check_schema_sanity(self, order: DraftPurchaseOrder, errors: list[str]) -> None:
        if order.quantity <= 0:
            errors.append(f"Quantity must be positive, got {order.quantity}")
        if not order.reasoning.strip():
            errors.append("Order rejected: missing justification context from agent.")

    def _check_product_lifecycle(self, order: DraftPurchaseOrder, errors: list[str]) -> None:
        # prevents dead-stock procurement pipelines from running automatically
        status = self._inventory.get_product_status(order.sku)
        if status in (ProductStatus.DISCONTINUED, ProductStatus.SEASONAL_HOLD):
            errors.append(f"SKU {order.sku} is currently '{status.value}' — ordering blocked.")

    def _check_warehouse_constraints(self, order: DraftPurchaseOrder, errors: list[str]) -> None:
        # hard check against actual bin/shelf space availability
        available = self._inventory.get_available_stock(order.sku)
        if order.quantity > available:
            errors.append(f"Requested {order.quantity} units, but warehouse max capacity is {available}.")

    def _verify_cited_sales_data(self, order: DraftPurchaseOrder, warnings: list[str]) -> None:
        # cross-checks the time range the agent claimed to analyze against the real DB
        actual = self._inventory.get_actual_sales_velocity(order.store_id, order.sku, order.cited_sales_window)
        if actual is None:
            warnings.append(f"Could not verify cited sales window '{order.cited_sales_window}' against DB.")

    def _check_order_size_anomaly(self, order: DraftPurchaseOrder, warnings: list[str]) -> None:
        # catches sudden spikes or massive deviations from recent store order baselines
        history = self._inventory.get_recent_order_sizes(order.store_id, order.sku)
        if not history:
            return
        typical_max = max(history)
        if order.quantity > typical_max * self.ANOMALY_MULTIPLIER:
            warnings.append(f"Quantity {order.quantity} is an anomaly ({order.quantity / typical_max:.1f}x typical max).")


# EXECUTION SIMULATION BLOCK

if __name__ == "__main__":
    import json

    # mock database implementations for simulation testing
    class MockDB:
        def get_status(self, sku): 
            return ProductStatus.DISCONTINUED if sku == "SKU_OLD" else ProductStatus.ACTIVE
        def get_quantity(self, sku): 
            return 1200
        def get_past_order_quantities(self, store, sku, days): 
            return [50, 60, 55]
        def get_units_sold(self, store, sku, window): 
            return None if "fake" in window else 150

    # wire up components
    mock_sys = InventorySystem(MockDB(), MockDB(), MockDB())
    validator = PurchaseOrderValidator(mock_sys)

    # test case 1: triggering a hard error (discontinued product)
    bad_order = DraftPurchaseOrder(
        store_id="STORE_01",
        sku="SKU_OLD",
        quantity=10000,
        reasoning="Sales trend dictates a large restock.",
        cited_sales_window="2026-06-01:fake_window"
    )

    # test case 2: simulate a normal operational workflow pass
    good_order = DraftPurchaseOrder(
        store_id="STORE_01",
        sku="SKU_ACTIVE",
        quantity=100,
        reasoning="Standard seasonal restock based on historical performance.",
        cited_sales_window="2026-06-01:2026-06-30"
    )

    print("RUNNING ENGINE VALIDATION EVALUATIONS\n")
    
    for i, test_order in enumerate([bad_order, good_order], 1):
        evaluation = validator.validate(test_order)
        print(f"--- Case {i} | SKU: {test_order.sku} ---")
        print(f"Is Valid to Process?       : {evaluation.is_valid}")
        print(f"Requires Human Inspection? : {evaluation.requires_human_approval}")
        print(f"Errors Caught              : {evaluation.errors}")
        print(f"Warnings Logged            : {evaluation.warnings}\n")